# Generated by Django 3.2.7 on 2021-09-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0002_auto_20210925_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='name',
            new_name='evo_name',
        ),
    ]
