# Generated by Django 3.2.7 on 2021-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0003_rename_name_evolution_evo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='evo_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='evolution',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='evolution',
            name='evo_chain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evo_chain',
            field=models.IntegerField(null=True),
        ),
    ]
