# Generated by Django 3.2.7 on 2021-09-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0004_auto_20210925_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolution',
            name='evo_chain',
        ),
    ]
