# Generated by Django 3.2.7 on 2021-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0005_remove_evolution_evo_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='poke_id',
            field=models.IntegerField(unique=True),
        ),
    ]
